### ISSUE TITLE
APNG instead of GIF

### ISSUE THREAD

**Issue by ghost** [syncopika/gifCatch_desktop-Windows-#7]
why don't you use APNG instead? it is a better format than GIF

**Comment by syncopika** [comment]
hmm that's worth considering I suppose. I only found out about APNG fairly recently and it never crossed my mind to use it here lol (so thanks!).

But also I think it's a bit of a convenience to use gif as I think gifs are more common and widely supported in common image viewer apps like Windows Photos. 

Additionally, creating gifs was made super easy with the help of https://github.com/charlietangora/gif-h; I'm not sure there's anything equivalent atm for APNG files specifically.
